codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
        flags:
          - unittests
    patch:
      default:
        target: 90%
        threshold: 1%
        base: auto
        flags:
          - unittests

  ignore:
    - "**/*.Tests.cs"
    - "**/bin/**"
    - "**/obj/**"
    - "TestResults/**"
    - "BrickLink.Client.Tests/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true